[package]
name          = "oidn-cli"
version       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
license       = { workspace = true }
authors       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
readme        = { workspace = true }
keywords      = ["denoising", "raytracing", "cli", "wgpu", "oidn"]
categories    = ["command-line-utilities", "graphics", "multimedia::images"]
description   = "Command-line image denoiser using oidn-rs"

[[bin]]
name = "oidn-rs"
path = "src/main.rs"

[dependencies]
burn      = { workspace = true }
oidn-tza  = { path = "../oidn-tza", version = "0.1.0" }
oidn-rs   = { path = "../oidn-rs",  version = "0.1.0" }
clap      = { workspace = true }
image     = { workspace = true }
exr-image = { workspace = true }
exr-core  = { workspace = true }
imath-rs  = { workspace = true }
half      = { workspace = true }
serde_json = "1"
tracing   = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wgpu      = "30"
pollster  = "0.4"
